version: '3.2'

services:
  agent:
    image: ghcr.io/ajnart/homarr:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  homarr:
    image: ghcr.io/ajnart/homarr:latest
    ports:
      - '7575:7575'
    volumes:
      - type: bind
        source: /mnt/homarr
        target: /data
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
    #   - /home/ubuntu/docker/homarr/configs:/app/data/configs
    #   - /home/ubuntu/docker/homarr/icons:/app/public/icons
    #   - /home/ubuntu/docker/homarr/data:/data
    networks:
      - agent_network 
    restart: unless-stopped  
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]


networks:
  agent_network:
    driver: overlay
    attachable: true