version: '3.2'

services:
  agent:
    image: germannewsmaker/myspeed
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  myspeed:
    image: germannewsmaker/myspeed
    ports:
      - "5216:5216"
    volumes:
      - /home/ubuntu/docker/myspeed:/data
    networks:
      - agent_network
    restart: unless-stopped  
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  agent_network:
    driver: overlay
    attachable: true