services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
      - WEBUI_PORT=8080
    volumes:
      - /home/abeksis/docker/config:/config
      - /mnt/data/torrents:/torrents
    ports:
      - 8080:8080
      - 26881:6881
      - 26881:6881/udp
    restart: unless-stopped