version: '3.8'
services:
    joal:
      image: anthonyraymond/joal
      container_name: joal
      restart: unless-stopped
      environment:
        - joal.ui.path.prefix=avi
        - joal.ui.secret-token=avi.net
        - spring.main.web-environment=true
        - server.port=6687
      volumes:
        - /home/abeksis/docker/joal/data:/data
      ports:
        - 6687:6687
      #command: ["--joal-conf=/data", "--spring.main.web-environment=true", "--server.port=6687", "--joal.ui.path.prefix=avi", "--joal.ui.secret-token=avi.net"]