version: "3.8"

services:

  joal:
    image: docker.io/anthonyraymond/joal:latest
    container_name: joal
    hostname: joal
    environment:
      - joal-conf=/data
      - spring.main.web-environment=true
      - server.port=20026
      - joal.ui.path.prefix=avi
      - joal.ui.secret-token=asdasd636a
    volumes:
      - /home/abeksis/docker/joal:/data

    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.joal.entrypoints=web"
      - "traefik.http.routers.joal.rule=Host(`joal.local.abeksis.work`)"
      - "traefik.http.middlewares.joal-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.joal.middlewares=joal-https-redirect"
      - "traefik.http.routers.joal-secure.entrypoints=websecure"
      - "traefik.http.routers.joal-secure.rule=Host(`joal.local.abeksis.work`)"
      - "traefik.http.routers.joal-secure.tls=true"
      - "traefik.http.routers.joal-secure.tls.certresolver=mydnschallenge"
      - "traefik.http.routers.joal-secure.service=joal"
      - "traefik.http.services.joal.loadbalancer.server.port=20026"
      - "traefik.docker.network=proxy"
    restart: unless-stopped

networks:
  proxy:
    external: true
