services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Asia/Jerusalem
      - ADVERTISE_IP=http://192.168.1.90:32400/
      - HOSTNAME=PlexServer
    volumes:
      - /home/abeksis/docker/plex:/config
      - /home/abeksis/docker/plex/transcode:/transcode
      - /home/abeksis/data/media:/data/media
      - /home/abeksis/data/media:/Private