version: '3'
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/abeksis/docker/homarr/configs:/app/data/configs
      - /home/abeksis/docker/homarr/icons:/app/public/icons
      - /home/abeksis/docker/homarr/data:/data
    ports:
      - '7575:7575'