version: "3"
services:
  myspeed:
    image: germannewsmaker/myspeed
    ports:
      - "5216:5216"
    volumes:
      - myspeed_data:/myspeed/data
    restart: unless-stopped
volumes:
  myspeed_data:
    driver: local