version: '3.8'
services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    cap_add:
      - NET_ADMIN
    networks:
      macvlan_NET:
        ipv4_address: 192.168.1.202
    volumes:
      - //home/abeksis/docker/adguard/work:/opt/adguardhome/work
      - /home/abeksis/docker/adguard/conf:/opt/adguardhome/conf
    restart: unless-stopped

networks:
    macvlan_NET:
      driver: macvlan
      driver_opts:
        parent: ens18
      ipam:
        config:
          - subnet: 192.168.1.0/24
            gateway: 192.168.1.1
            ip_range: 192.168.1.0/24