
version: "2"
services:
  joal:
    image: anthonyraymond/joal:2.1.36
    container_name: joal
    restart: unless-stopped
    volumes:
      - /home/abeksis/docker/joal:/data
    ports:
      - PORT:PORT
    command: ["--joal-conf=/data", "--spring.main.web-environment=true", "--server.port=PORT", "--joal.ui.path.prefix=avi", "--joal.ui.secret-token=avi.net"]