version: "3"
services:
  myspeed:
    image: germannewsmaker/myspeed
    ports:
      - "5216:5216"
    volumes:
      - /home/abeksis/docker/myspeed:/data
    restart: unless-stopped
volumes:
  myspeed_data:
    driver: local