services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - /home/abeksis/docker/sonarr:/config
      - /home/abeksis/data/media/tv:/tv
      - /home/abeksis/data/torrents:/data/torrents
    network_mode: bridge  
    ports:
      - 8989:8989
    restart: unless-stopped