version: '3.2'

services:
  agent:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]


  watchtower:
    image: containrrr/watchtower:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    # ports:
    #   - "5216:5216"
    volumes:
      - type: bind
        source: /mnt/watchtower
        target: /data
    environment:
        TZ: "Asia/Jerusalem"
        WATCHTOWER_CLEANUP: "true"
        WATCHTOWER_SCHEDULE: "0 0 5 * * *"
        WATCHTOWER_NOTIFICATIONS: "shoutrrr"
        WATCHTOWER_NOTIFICATION_URL: "telegram://${MY_DOCKER_BOT_TOKEN}@telegram?channels=${TELEGRAM_CHAT_ID}"
        WATCHTOWER_WARN_ON_HEAD_FAILURE: "never"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock            
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  agent_network:
    driver: overlay
    attachable: true